
# base not defined

# clients settings
clients:
  type: simple # type
  total_clients: 50 # total number of clients
  per_round: 40 # number of clients selected in each round
  do_test: False # Should clients compute test accuracy locally?

# server settings
server:
  address: 127.0.0.1
  port: 8000

# dataset settings for the multimodal data, frames, flow, and audio
data:
  datasource: kinetics700
  path: ./data/Kinetics
  download_url: https://storage.googleapis.com/deepmind-media/Datasets/kinetics700_2020.tar.gz
  num_workers: 4
  failed_save_file: !file failed_record.txt
  log_file: !file download_log.txt
  compress: False
  verbose: False
  skip: False
  videos_per_gpu: 3
  workers_per_gpu: 4
  sampler: dis_noniid
  modality_sampler: modality_iid

# Train settings

# optimizer
optimizer: &optimizer
  type: SGD
  lr: 0.000125 # this lr is used for 8 gpus
  momentum: 0.9
  weight_decay: 0.0001

optimizer_config: &optimizer_config
  grad_clip:
    max_norm: 40
    norm_type: 2

# learning policy
lr_configs: &lr_config
  policy: step
  step:
    1. 32
    2. 48

  warmup: linear
  warmup_ratio: 0.1
  warmup_by_epoch: True
  warmup_iters: 16

total_epochs: &total_epochs
  1000

log_config:
  interval: 20
  hooks:
    1. type: TextLoggerHook
    2. type: TensorboardLoggerHook

trainer:
  type: basic
  batch_size: 24
  optimizer: *optimizer
  optimizer_config: *optimizer_config
  learning_rate_config: *lr_config
  rounds: *total_epochs
  parallelized: False
  max_accuracy: clients.per_round
  target_accuracy: 0.67

checkpoint_config:
  interval: 2

evaluation:
  interval: 5
  metrics:
    1. top_k_accuracy
    2. mean_class_accuracy
  
algorithm:
  type: fedavg
# Aggregation algorithm
# The number of local aggregation rounds on edge servers before sending
# aggreagted weights to the central server 


# runtime setting
runner_setting:
  dist_params:
    backend: nccl
    log_level: INFO
    work_dir: ./work_dirs/mmf # noqa: E501
    load_from: null
    resume_from: null
    workflow:
      1. train
      2. 1
    find_unused_parameters: True
