clients:
    # Type
    type: simple

    # The total number of clients
    total_clients: 3

    # The number of clients selected in each round
    per_round: 2

    # Should the clients compute test accuracy locally?
    do_test: true

server:
    address: 127.0.0.1
    port: 8000

data:
    # The training and testing dataset
    datasource: CIFAR10

    # Where the dataset is located
    data_path: ./data

    # Maximum number of samples in each partition
    max_partition_size: 40000

    # Minimum number of samples in each partition
    min_partition_size: 10000

    # IID or non-IID?
    sampler: label_distribution_noniid

    # The concentration parameter for the Dirichlet distribution
    concentration: 500

    # The random seed for sampling data
    random_seed: 1

trainer:
    # The type of the trainer
    type: basic

    # The maximum number of training rounds
    rounds: 10000

    # Whether the training should use multiple GPUs if available
    parallelized: true

    # The maximum number of clients running concurrently
    max_concurrency: 2

    # The target accuracy
    target_accuracy: 0.88

    # Number of epoches for local training in each communication round
    epochs: 5
    batch_size: 128
    optimizer: Adam
    learning_rate: 0.01
    momentum: 0.9
    weight_decay: 0.0

    # The machine learning model
    model_name: vgg_16
    num_classes: 10

algorithm:
    # Aggregation algorithm
    type: fedavg
