clients:
    # The total number of clients
    total_clients: 5 # 50

    # The number of clients selected in each round
    per_round: 3 # 20
    
    # Should the clients compute test accuracy locally?
    # we set it false here because we implement other
    #   test methods. And, we do not want to use 
    #   the test code in the simple Client
    do_test: false

    # selected clients for test
    test_clients: 2 # 20
    

server:
    address: 127.0.0.1
    port: 8000

data:
    # The training and testing dataset
    datasource: FashionMNIST

    # Where the dataset is located
    data_path: ../../data

    # Number of samples in each partition
    partition_size: 20000

    # IID or non-IID?
    sampler: quantity_label_nonIID

    # The random seed for sampling data
    random_seed: 1

    # this is for the quantity label noniid
    per_client_classes_size: 4

    # The number of consistent clients
    consistent_clients_size: 2 # 20

trainer:
    # The maximum number of training rounds
    rounds: 1000

    # the number of rounds to compute the meta personalization once
    meta_test_round_interval: 2


    # the local update steps that is the tau in the paper
    local_update_steps: 4

    # Whether the training should use multiple GPUs if available
    parallelized: false

    # The maximum number of clients running concurrently
    max_concurrency: 2 

    # The target accuracy
    target_accuracy: 0.98

    # Number of epoches for local training in each communication round
    epochs: 4
    batch_size: 40
    optimizer: SGD
    learning_rate: 0.01
    momentum: 0.9
    weight_decay: 0.0

    meta_learning_rate: 0.01

    # The machine learning model
    model_name: lenet5

algorithm:
    # Aggregation algorithm
    type: fedavg

results:
    # Write the following parameter(s) into a CSV
    types: accuracy, personalization_accuracy, training_time, round_time
