clients:

    # The total number of clients
    total_clients: 100

    # The number of clients selected in each round
    per_round: 10

    # Should the clients compute test accuracy locally?
    do_test: true


server:

    type: fedavg_personalized
    address: 127.0.0.1
    port: 8002

    do_test: false
    

data:
    # The training and testing dataset
    datasource: CIFAR10

    # The random seed for sampling data
    random_seed: 1

trainer:

    # The maximum number of training rounds
    rounds: 200

    # The maximum number of clients running concurrently
    max_concurrency: 2

    # The target accuracy
    target_accuracy: 0.94

    # The machine learning model
    model_name: convnext_base_w
    pretrained_dataset: laion2b_s13b_b82k_augreg

algorithm:
    # Aggregation algorithm
    type: fedavg_partial


parameters:
    optimizer:
        lr: 0.03
        momentum: 0.9
        weight_decay: 0.0

    learning_rate:
        gamma: 0.1
        milestone_steps: 150ep,350ep

    loss_criterion:
        label_smoothing: 0.5

    model:
        num_classes: 10
